# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/wr786"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Eventernote"
name = "Eventernote"
url = "https://www.eventernote.com/users/NANAKOWA"
