# PaperMod configuration
env = "production"
description = "wr786"
author = "wr786"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = false
ShowPageNums = true
ShowToc = true
TocOpen = false
comments = true
images = ["/favicon.png"]

[assets]
favicon = "/favicon.png"
favicon16x16 = "/favicon.png"
favicon32x32 = "/favicon.png"
disableHLJS = true

[homeInfoParams]
Title = "wr786"
Content = "Comment te dire adieu"

[[socialIcons]]
name = "github"
title = "GitHub"
url = "https://github.com/wr786"

[[socialIcons]]
name = "link"
title = "Eventernote"
url = "https://www.eventernote.com/users/7KoWa"
